### ISSUE TITLE
💫  Set up proper testing on Appveyor

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#1212]
A while ago, we finally set up spaCy [on Appveyor](https://ci.appveyor.com/project/explosion/spacy) again to do proper Windows testing. The badge and `.appveyor.yml` already exist, but it's currently set to `build: off` and doesn't run any tests. This needs to be fixed. There's an old version of spaCy's previous `.appveyor.yml` available [in the history here](https://github.com/explosion/spaCy/blob/66765d4d8f0828ea0b07a1d81e4375600ea66ac5/.appveyor.yml).

## Todos
- [ ] See if the old `.appveyor.yml` configuration still works.
- [ ] If not, adjust it accordingly.
- [ ] **Bonus:** Include commands for model downloads? (Might not make much sense for v1.x, as the models are very large and may cause timeouts and confusing build failures. But going forward, the v2.0 models of 10-20MB each could easily be tested this way on both Appveyor and Travis.)

**Comment by Liebeck** [comment]
@ines: I'm using Appveyor for a C# project and can link you the solution that I came up with https://github.com/Liebeck/IWNLP/blob/master/appveyor.yml  
It's not the cleanest version but it should point you into the right direction concerning downloading and caching a model. By the way: The cache is only updated if the build passes. This has cost me some time in the past ^^

**Comment by ines** [comment]
@Liebeck Thanks for sharing – this is super helpful! 👍

(I finally opened this issue to stop us from procrastinating on this, haha. Writing and debugging CI config files is definitely not the most fun, but it really needs to be done for the v2 release.)
