### ISSUE TITLE
Fix Keras examples

### ISSUE THREAD

**Issue by ines** [explosion/spaCy#2758]
There are various issues with the [`keras_parikh_entailment`](https://github.com/explosion/spaCy/tree/master/examples/keras_parikh_entailment) and [`deep_learning_keras.py`](https://github.com/explosion/spaCy/blob/master/examples/deep_learning_keras.py) examples. Those should be investigated, and we should probably rewrite the examples to ensure they work with the latest versions of both Keras and spaCy.

### Related issues

- [x] #2743: Errors while running spacy with keras example
- [x] #2501: Deep learning with keras Sentiment analysis
- [ ] #2383: Testing of keras_parikh_entailment model
- [ ] #2371: Unable to run demo of keras_parikh_entailment example through python
- [ ] #2362: Error while running evaluate on keras_parikh_entailment
- [x] #2209: Different problems to test "Text classification with Keras" example 
- [x] #1917: More guidance needed re deep_learning_keras.py example
- [ ] #1445: Port decomposable attention to Keras v2

**Comment by free-variation** [comment]
For #2501 I have a fix that works with python3.5.2 and spaCy 2.0.12.  

The ref is [here](https://github.com/free-variation/spaCy/commit/0d4760dc199d4ce82c1f24d03bbef62f1f1f14ee).

Should I issue a PR for just this one example or look at some more of the issues listed here?

**Comment by free-variation** [comment]
@ines I submitted a PR -- my first for this project, so I hope I filled out the PR as you expect -- and will now look at the Parikh issues.

**Comment by free-variation** [comment]
@ines and @honnibal  in terms of the Parikh examples (#2383 #2371 #2362 #1445), I wonder if you might provide some guidance.

I have working code implementing the Parikh model.  The fact though is that I re-wrote it from scratch.  The reasons are:

- I wanted to make sure I quite understood the paper, by producing an implementation that adheres fairly closely to the paper, including notation.
- There are elements in the existing example that I'm not sure that I understand, some of which appear to go beyond the Parikh et al paper.
- The API changes in recent Keras seem significant enough that a straight refactor seemed difficult.
- I wanted to investigate whether a further simplification to the original model, that exploits the asymmetry of entailment, would perform as well as the base model.

I've captured the results [here](https://github.com/free-variation/spaCy/blob/master/examples/notebooks/Decompositional%20Attention.ipynb)

My questions now are:

1. Is this re-write useful for the spaCy project?
2. If so, shall I "productify" this implementation by turning the iPython notebook into runnable scritps, on the model of the current example (__main__.py etc.) ?

Thank you.

**Comment by honnibal** [comment]
@free-variation Sorry for the delay replying, and thanks for your efforts here.

First, to answer your questions:

> Is this re-write useful for the spaCy project?

Yes. It's a good paper and it'll be great to get a non-trivial example of Keras+spaCy working again.

> If so, shall I "productify" this implementation by turning the iPython notebook into runnable scritps, on the model of the current example (__main__.py etc.) ?

Yes, ideally getting it to work with the hook etc, so that it can be used to provide `doc.similarity()` estimates. We do much prefer scripts to notebooks for our examples, as it's easier to get running code from them.

Additionally, some more general thoughts:

It's true that my implementation had a number of bits and pieces that went beyond the original paper. I do regret not drawing a cleaner line there --- it was tempting to try things out, but I should've done that in a separate example file, or on a branch.

I will say that it's very difficult to replicate Parikh's result of 86%. I never got there. I think the optimization is quite sensitive. It's also difficult to implement the model correctly, due to the difficulty of ensuring that the sentence padding doesn't interfere with the averaging. This was actually the last thing I wrote with Keras, for exactly that reason. I think the way Keras does variable-length sequences is quite broken, which is a huge problem for NLP.

One idea I've tried that did help is to truncate the sentences by distance from the root in the syntactic tree, rather than by length. This is good because a length-based truncation risks missing out on the main verb, which is always going to be problematic. The code for this was something like:

```python

def tree_truncate(doc, max_length):
    '''Get a limited number of words from a doc, trimming words lowest in the tree.'''
    if len(doc) < max_length:
        return [t.text for t in doc]    
    # Get tuples of (depth, i, text). We need the position i
    # so we can re-sort by it after the truncation.
    by_depth = [(len(token.ancestors), token.i, t.text) for token in doc]
    by_depth.sort()
    by_depth = by_depth[:max_length]
    by_position = [(i, text) for i, text in by_height]
    by_position.sort()
    return [text for i, text in by_position]
 ```

If you try this out, you might play with very aggressive truncations (like, max 15). This should prefer to trim determiners and other deep modifiers, while keeping more relevant words.

**Comment by free-variation** [comment]
I've hit 86+% after fixing a bug.  All good -- this method works.  I'm going to script-ize it all now.

jds

**Comment by free-variation** [comment]
@honnibal I wanted to clear up an issue.  Above, when you remarked on `doc.similarity()`, and also in comments I'm seeing in the existing example code, you refer to this method establishing "similarity", presumably a symmetric concept.  

Now, it's true that the Parikh paper implements a symmetric operation, a sort of bidirectional entailment.  However, the SNLI is directed towards asymmetric entailment, and in my notebook I show that an asymmetric revision (simplification, actually) of the Parikh model performs the same as the original model.

So we could say this is "similarity", but end up training an asymmetric model.  What are your thoughts?

**Comment by honnibal** [comment]
> So we could say this is "similarity", but end up training an asymmetric model. What are your thoughts?

This is true, and in other work I've tried training a symmetric model instead of this asymmetric one. Maybe it's misleading to frame this as similarity, especially since these supervised methods don't actually do very well at capturing similarity outside of the way entailment is used in the dataset.

**Comment by honnibal** [comment]
By the way, if you want to go deeper on these similarity questions, there's another notable weakness of this specific model.

In your experiments, consider the way unknown words are handled. It's common in NLP models to map all unknown words to the same vector. This is very unideal in these entailment models, since it means the model loses the ability to see that two rare words match across the inputs. Matching rare words are a very good indicator.

One solution is to use the word ID to see a RNG, so that you can draw a new arbitrary vector for each unseen word type, while ensuring that tokens of the same type receive a consistent representation.

**Comment by free-variation** [comment]
@honnibal Yes, I've run into many issues with the SNLI.  One shouldn't forget that the "NL" in the acronym is "natural logic", so we're really just talking about the monotonicity calculus. 

- I frequently find the pairs that are marked "contradiction" to be a little confusing.  Maybe they're about "opposition", but sometimes I fail to see much of any link between the propositions.  It may be better to reduce the problem to a binary decision (and perhaps then rebalance the corpus, though that would cut its size by 1/3).
- The texts, from Flickr, are generally flat descriptions of a scene: "Two women are ...".  This is a specific form of discourse: in the present tense, requiring little world knowledge, referring to visual input and not, say, concepts.

The RTE tasks seem to require a richer model of entailment.  It would be interesting to test the Parikh model on those.  I'll take a look, if I can find the datasets.

**Comment by free-variation** [comment]
@honnibal With respect to the OOV problem, in Parikh et al, as you'll recall, they randomly assign unknown words to one of `nr_unk=100` randomly generated vectors.  I used the same approach, with the slight alteration that I use `token.rank % nr_unk` to index OOV terms into the random block, so the same token will get the same vector.  

Nevertheless, with only 100 slots, this means that words that have nothing to do with each other will still be mapped to the same vector.  Your solution of using a random seed is really cool!  This was one can reconstruct the vector.  The trouble is that, in practice, one would still need to push all those OOV vectors into the embeddings matrix in GPU memory, which I fear would explode.  The 1MM vectors in `en-vectors-web-lg` already take up 1.2GB.

**Comment by free-variation** [comment]
Finally, @honnibal, I wonder if there are more papers of this sort you'd like to see materialized in spaCy.  As end-to-end models take hold, the demand for sophisticated feature-generation (syntactic parsing etc.) might drop, perhaps.  I don't know if that's true.

Still, it may be useful for systems like spaCy, Stanford CoreNLP, OpenNLP etc. to move up the food chain and build in higher-level modules that accomplish tasks users are trying to build themselves.
